<?
//Grouping models by names (hard grouping - subname including)
$arHardGroups = Array(
	"VW" => Array("NEW BEETLE", "L 80"),
	"CHRYSLER" => Array("CARAVAN","VOYAGER"),
	"HUMMER" => Array("H1","H2","H3"),
	"HYUNDAI" => Array("SANTA FE","SANTA FÉ","H 150","H 200","AERO CITY","AERO TOWN","SUPER AERO CITY"),
	"MITSUBISHI" => Array("L 200","L 300","L 400","PAJERO SPORT","PROUDIA DIGNITY","SPACE GEAR","SPACE RUNNER","SPACE STAR","SPACE WAGON","TOWN"=>"TOWN BOX","3000 GT"),
	"SUZUKI"=>Array("GRAND ESCUDO","GRAND VITARA","LJ 81","MIGHTY BOY","MR WAGON","SA 310","SUPER CARRY","WAGON R","SJ 410","SJ 413"),
	"TOYOTA"=>Array("4 RUNNER","FJ CRUISER","FUN CARGO","LAND CRUISER","MASTER ACE SURF","MEGA CRUISER","MODELL F","RAV 4","SOLUNA VIOS","TAMARAW FX","TOWN ACE","TOYOTA 86","URBAN CRUISER"),
	"VOLVO" => Array("440 K","460 L","480 E","F 16","FS 7","NH 12"),
	"PEUGEOT"=>Array("GRAND RAID"),
	"FIAT"=>Array("L Serie","TL Serie","66 Serie","88 Serie","90 Serie","94 Serie"),
	"MAZ"=>Array("Serie 100","Serie 170","Serie 200"),
	"MAN"=>Array("E 2000","G 90","L 2000","LION S","SL II"),
	"SCANIA"=>Array("2 - series","3 - series","4 - series","IRIZAR PB","P,G,R,T - series"),
	"FORD"=>Array("ECOSPORT II", "GRAND C-MAX", "STREET KA"),
	"HONDA"=>Array("EV PLUS"),
	"RENAULT"=>Array("EURO CLIO III","GRAN TOUR III"),
);
//Rename model group - move to other group...
$arRenamesRegroup = Array(
	"ALFA_ROMEO" => Array("GTV-6"=>"GTV"),
	"BMW" => Array("ALPINA"=>"ALPINA B7","GRAND"=>"GRAND COUPE","GRAN"=>"GRAN TURISMO"),
	"CHRYSLER" => Array("300M"=>"300", "CHRYSLER"=>"CHRYSLER R/T", "GS"=>"DAYTONA", "E"=>"E CLASS", "LEBARON"=>"LE BARON", "LE"=>"LE BARON", "NEW"=>"NEW YORKER", "PT"=>"PT CRUISER", "TC"=>"TC MASERATI", "TOWN"=>"TOWN & COUNTRY"),
	"BUICK" => Array("LA"=>"LACROSSE","LE"=>"LESABRE","PARK"=>"PARK AVENUE","RENDEZVOUZ"=>"RENDEZVOUS"),
	"CADILLAC" => Array("COMMERCIAL"=>"COMMERCIAL CHASSIS","60"=>"60 SPECIAL"),
	"CHEVROLET" => Array("MODEL"=>"MODEL P", "MONTE"=>"MONTE CARLO"),
	"DODGE" => Array("GRAND"=>"GRAND CARAVAN","Ram"=>"RAM", "H"=>"H 100", "H100"=>"H 100","W100"=>"W","W150"=>"W","W250"=>"W","W350"=>"W","i"=>"i10"),
	"FERRARI" => Array("5__"=>"5__ MARANELLO", "612"=>"612 SCAGLIETTI"),
	"FIAT" => Array("PRÈMIO"=>"PREMIO", "GRANDE"=>"GRANDE PUNTO"),
	"FORD" => Array("CROWN"=>"CROWN VICTORIA","F"=>"F SUPER DUTY", "P"=>"P 100"),
	"HAFEI" => Array("SAIMA"=>"SAIMA/SIGMA","SIGMA"=>"SAIMA/SIGMA"),
	"HONDA" => Array("Ballade"=>"BALLADE IV","BALLADE"=>"BALLADE IV"),
	"HYUNDAI" => Array("SANTA FÉ"=>"SANTA FE","GRAND"=>"GRAND STAREX","SOLARIS"=>"SOLARIS IV"),
	"JEEP" => Array("GRAND"=>"GRAND CHEROKEE"),
	"KIA" => Array("CEE'D"=>"CEED","CEE`D"=>"CEED","PRO"=>"PRO CEED","Spectra"=>"SPECTRA","RIO5"=>"RIO","SPECTRA5"=>"SPECTRA"),
	"LAMBORGHINI" => Array("MURCIÉLAGO"=>"MURCIELAGO"),
	"LAND_ROVER" => Array("RANGE"=>"RANGE ROVER"),
	"LINCOLN" => Array("TOWN"=>"TOWN CAR"),
	"MASERATI" => Array("3200"=>"3200 GT"),
	"MAZDA" => Array("RX-7"=>"RX","RX-8"=>"RX"),
	"MERCEDES-BENZ" => Array("C"=>"C-CLASS","R"=>"R-CLASS"),
	"MITSUBISHI" => Array("PAJERO/SHOGUN"=>"PAJERO","SHOGUN"=>"PAJERO SPORT","L300"=>"L 300","MIGHTY"=>"MIGHTY MAX","LIBERO"=>"LIBERO V","3000GT"=>"3000 GT"),
	"NISSAN" => Array("300"=>"300ZX","200"=>"240SX","350"=>"350Z","370"=>"370Z","FAIRLADY"=>"FAIRLADY Z","Gazelle"=>"GAZELLE","NV200"=>"NV","NV400"=>"NV","PICK"=>"PICKUP","100"=>"100 NX","240"=>"240 SX","180"=>"180 SX","1400"=>"1400 BAKKIE"),
	"OPEL" => Array("CALIBRA"=>"CALIBRA A"),
	"PEUGEOT" => Array("206+"=>"206"),
	"PORSCHE" => Array("CARRERA"=>"CARRERA GT"),
	"RENAULT" => Array("SCÉNIC"=>"SCENIC","GRAND"=>"GRAND SCENIC","SUPER"=>"SUPER 5","TONDAR"=>"TONDAR 90","SPORT"=>"SPORT SPIDER","RODEO"=>"RODEO 5","EURO"=>"EURO CLIO","VEL"=>"VEL SATIS"),
	"ROLLS-ROYCE" => Array("FLYING"=>"FLYING SPUR","PARK"=>"PARK WARD","TOURING"=>"TOURING LIMOUSINE"),
	"SUBARU" => Array("MINI"=>"MINI JUMBO"),
	"SUZUKI" => Array("SJ410"=>"SJ 410"),
	"TOYOTA" => Array("4RUNNER"=>"4 RUNNER","MR2"=>"MR","RAV4"=>"RAV 4","VAN"=>"VAN Mini"),
	
);
?>